/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package OnlineShop {
    final case class ProductDescription(name: ` lfdomainapi`.Primitive.Text, description: ` lfdomainapi`.Primitive.Text, imageUrl: ` lfdomainapi`.Primitive.Text) extends ` lfdomainapi`.Template[ProductDescription] {
      override protected[this] def templateCompanion(implicit ` d` : ` lfdomainapi`.Compat.DummyImplicit) = ProductDescription
    }

    object ProductDescription extends ` lfdomainapi`.TemplateCompanion[ProductDescription] with _root_.scala.Function3[` lfdomainapi`.Primitive.Text, ` lfdomainapi`.Primitive.Text, ` lfdomainapi`.Primitive.Text, _root_.com.daml.quickstart.iou.model.OnlineShop.ProductDescription] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val name: ` C`[` lfdomainapi`.Primitive.Text];
        val description: ` C`[` lfdomainapi`.Primitive.Text];
        val imageUrl: ` C`[` lfdomainapi`.Primitive.Text];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val name = ` f`(` view`.name);
            override val description = ` f`(` view`.description);
            override val imageUrl = ` f`(` view`.imageUrl)
          };
          new $anon()
        }
      };
      override val id = ` templateId`(packageId = `Package IDs`.OnlineShop, moduleName = "OnlineShop", entityName = "ProductDescription");
      final implicit class `ProductDescription syntax`[+` ExOn`](private val id: ` ExOn`) extends _root_.scala.AnyVal {
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party, choiceArgument: com.daml.quickstart.iou.model.DA.Internal.Template.Archive)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, ProductDescription]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = ` exercise`(actor, id, "Archive", _root_.scala.Some(` lfdomainapi`.Value.encode(choiceArgument)));
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, ProductDescription]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = exerciseArchive(actor, _root_.com.daml.quickstart.iou.model.DA.Internal.Template.Archive())
      };
      type key = ` lfdomainapi`.Primitive.Text;
      override val consumingChoices: _root_.scala.collection.immutable.Set[` lfdomainapi`.Primitive.ChoiceId] = ` lfdomainapi`.Primitive.ChoiceId.subst(_root_.scala.collection.immutable.Set("Archive"));
      override def toNamedArguments(` self` : ProductDescription) = ` arguments`(scala.Tuple2("name", ` lfdomainapi`.Value.encode(` self`.name)), scala.Tuple2("description", ` lfdomainapi`.Value.encode(` self`.description)), scala.Tuple2("imageUrl", ` lfdomainapi`.Value.encode(` self`.imageUrl)));
      override def fromNamedArguments(` r` : ` rpcvalue`.Record) = if (` r`.fields.length.==(3))
        ` r`.fields(0) match {
          case ` rpcvalue`.RecordField((""| "name"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv0) match {
            case _root_.scala.Some(z0) => (` r`.fields(1) match {
              case ` rpcvalue`.RecordField((""| "description"), _root_.scala.Some(zv1)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv1) match {
                case _root_.scala.Some(z1) => (` r`.fields(2) match {
                  case ` rpcvalue`.RecordField((""| "imageUrl"), _root_.scala.Some(zv2)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv2) match {
                    case _root_.scala.Some(z2) => Some(ProductDescription(z0, z1, z2))
                    case _root_.scala.None => _root_.scala.None
                  })
                  case _ => _root_.scala.None
                })
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            })
            case _root_.scala.None => _root_.scala.None
          })
          case _ => _root_.scala.None
        }
      else
        _root_.scala.None;
      override def fieldEncoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): view[lte.Field] = {
        object `view ` extends view[lte.Field] {
          val name = lte.field("name", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte));
          val description = lte.field("description", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte));
          val imageUrl = lte.field("imageUrl", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte))
        };
        `view `
      };
      override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding)(`view `: view[lte.Field]): lte.Out[_root_.com.daml.quickstart.iou.model.OnlineShop.ProductDescription] = {
        val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.OnlineShop.ProductDescription] = lte.RecordFields.xmapN(lte.fields(`view `.name), lte.fields(`view `.description), lte.fields(`view `.imageUrl))({
          case scala.Tuple3(name, description, imageUrl) => _root_.com.daml.quickstart.iou.model.OnlineShop.ProductDescription(name, description, imageUrl)
        })({
          case _root_.com.daml.quickstart.iou.model.OnlineShop.ProductDescription(name, description, imageUrl) => scala.Tuple3(name, description, imageUrl)
        });
        lte.record(` dataTypeId`, `recordFields `)
      }
    }
  }
}
