/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package OnlineShop {
    final case class ProductOrder(customer: ` lfdomainapi`.Primitive.Party, productName: ` lfdomainapi`.Primitive.Text) extends ` lfdomainapi`.Template[ProductOrder] {
      override protected[this] def templateCompanion(implicit ` d` : ` lfdomainapi`.Compat.DummyImplicit) = ProductOrder
    }

    object ProductOrder extends ` lfdomainapi`.TemplateCompanion[ProductOrder] with _root_.scala.Function2[` lfdomainapi`.Primitive.Party, ` lfdomainapi`.Primitive.Text, _root_.com.daml.quickstart.iou.model.OnlineShop.ProductOrder] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val customer: ` C`[` lfdomainapi`.Primitive.Party];
        val productName: ` C`[` lfdomainapi`.Primitive.Text];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val customer = ` f`(` view`.customer);
            override val productName = ` f`(` view`.productName)
          };
          new $anon()
        }
      };
      override val id = ` templateId`(packageId = `Package IDs`.OnlineShop, moduleName = "OnlineShop", entityName = "ProductOrder");
      final implicit class `ProductOrder syntax`[+` ExOn`](private val id: ` ExOn`) extends _root_.scala.AnyVal {
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party, choiceArgument: com.daml.quickstart.iou.model.DA.Internal.Template.Archive)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, ProductOrder]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = ` exercise`(actor, id, "Archive", _root_.scala.Some(` lfdomainapi`.Value.encode(choiceArgument)));
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, ProductOrder]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = exerciseArchive(actor, _root_.com.daml.quickstart.iou.model.DA.Internal.Template.Archive())
      };
      type key = com.daml.quickstart.iou.model.DA.Types.Tuple2[` lfdomainapi`.Primitive.Party, ` lfdomainapi`.Primitive.Text];
      override val consumingChoices: _root_.scala.collection.immutable.Set[` lfdomainapi`.Primitive.ChoiceId] = ` lfdomainapi`.Primitive.ChoiceId.subst(_root_.scala.collection.immutable.Set("Archive"));
      override def toNamedArguments(` self` : ProductOrder) = ` arguments`(scala.Tuple2("customer", ` lfdomainapi`.Value.encode(` self`.customer)), scala.Tuple2("productName", ` lfdomainapi`.Value.encode(` self`.productName)));
      override def fromNamedArguments(` r` : ` rpcvalue`.Record) = if (` r`.fields.length.==(2))
        ` r`.fields(0) match {
          case ` rpcvalue`.RecordField((""| "customer"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Party](zv0) match {
            case _root_.scala.Some(z0) => (` r`.fields(1) match {
              case ` rpcvalue`.RecordField((""| "productName"), _root_.scala.Some(zv1)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv1) match {
                case _root_.scala.Some(z1) => Some(ProductOrder(z0, z1))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            })
            case _root_.scala.None => _root_.scala.None
          })
          case _ => _root_.scala.None
        }
      else
        _root_.scala.None;
      override def fieldEncoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): view[lte.Field] = {
        object `view ` extends view[lte.Field] {
          val customer = lte.field("customer", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Party](lte));
          val productName = lte.field("productName", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte))
        };
        `view `
      };
      override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding)(`view `: view[lte.Field]): lte.Out[_root_.com.daml.quickstart.iou.model.OnlineShop.ProductOrder] = {
        val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.OnlineShop.ProductOrder] = lte.RecordFields.xmapN(lte.fields(`view `.customer), lte.fields(`view `.productName))({
          case scala.Tuple2(customer, productName) => _root_.com.daml.quickstart.iou.model.OnlineShop.ProductOrder(customer, productName)
        })({
          case _root_.com.daml.quickstart.iou.model.OnlineShop.ProductOrder(customer, productName) => scala.Tuple2(customer, productName)
        });
        lte.record(` dataTypeId`, `recordFields `)
      }
    }
  }
}
