/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package OnlineShop {
    final case class Product_WithdrawReservation(reservation: com.daml.quickstart.iou.model.OnlineShop.Reservation) extends ` lfdomainapi`.ValueRef

    object Product_WithdrawReservation extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function1[com.daml.quickstart.iou.model.OnlineShop.Reservation, _root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val reservation: ` C`[com.daml.quickstart.iou.model.OnlineShop.Reservation];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val reservation = ` f`(` view`.reservation)
          };
          new $anon()
        }
      };
      implicit val `Product_WithdrawReservation Value`: ` lfdomainapi`.Value[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation] {
          override def write(value: _root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation): ` rpcvalue`.Value.Sum = ` record`(scala.Tuple2("reservation", ` lfdomainapi`.Value.encode(value.reservation)));
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation] = argValue.record.flatMap(((` r` ) => if (` r`.fields.length.==(1))
            ` r`.fields(0) match {
              case ` rpcvalue`.RecordField((""| "reservation"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[com.daml.quickstart.iou.model.OnlineShop.Reservation](zv0) match {
                case _root_.scala.Some(reservation) => Some(Product_WithdrawReservation(reservation))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            }
          else
            _root_.scala.None))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.OnlineShop, "OnlineShop", "Product_WithdrawReservation");
      implicit def `Product_WithdrawReservation LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation] = {
            object `view ` extends view[lte.Field] {
              val reservation = lte.field("reservation", ` lfdomainapi`.encoding.LfEncodable.encoding[com.daml.quickstart.iou.model.OnlineShop.Reservation](lte))
            };
            {
              val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation] = lte.RecordFields.xmapN(lte.fields(`view `.reservation))({
                case reservation => _root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation(reservation)
              })({
                case _root_.com.daml.quickstart.iou.model.OnlineShop.Product_WithdrawReservation(reservation) => reservation
              });
              lte.record(` dataTypeId`, `recordFields `)
            }
          }
        };
        new $anon()
      }
    }
  }
}
