/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET DAML SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package com.daml.quickstart.iou.model {
  package OnlineShop {
    final case class Product_ReservationCompleted(reservationId: ` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.OnlineShop.Reservation]) extends ` lfdomainapi`.ValueRef

    object Product_ReservationCompleted extends ` lfdomainapi`.ValueRefCompanion with _root_.scala.Function1[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.OnlineShop.Reservation], _root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val reservationId: ` C`[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.OnlineShop.Reservation]];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val reservationId = ` f`(` view`.reservationId)
          };
          new $anon()
        }
      };
      implicit val `Product_ReservationCompleted Value`: ` lfdomainapi`.Value[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted] = {
        final class $anon extends this.`Value ValueRef`[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted] {
          override def write(value: _root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted): ` rpcvalue`.Value.Sum = ` record`(scala.Tuple2("reservationId", ` lfdomainapi`.Value.encode(value.reservationId)));
          override def read(argValue: ` rpcvalue`.Value.Sum): _root_.scala.Option[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted] = argValue.record.flatMap(((` r` ) => if (` r`.fields.length.==(1))
            ` r`.fields(0) match {
              case ` rpcvalue`.RecordField((""| "reservationId"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.OnlineShop.Reservation]](zv0) match {
                case _root_.scala.Some(reservationId) => Some(Product_ReservationCompleted(reservationId))
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            }
          else
            _root_.scala.None))
        };
        new $anon()
      };
      override protected val ` dataTypeId` = ` mkDataTypeId`(`Package IDs`.OnlineShop, "OnlineShop", "Product_ReservationCompleted");
      implicit def `Product_ReservationCompleted LfEncodable`: ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted] = {
        final class $anon extends ` lfdomainapi`.encoding.LfEncodable[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted] {
          override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): lte.Out[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted] = {
            object `view ` extends view[lte.Field] {
              val reservationId = lte.field("reservationId", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.ContractId[com.daml.quickstart.iou.model.OnlineShop.Reservation]](lte))
            };
            {
              val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted] = lte.RecordFields.xmapN(lte.fields(`view `.reservationId))({
                case reservationId => _root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted(reservationId)
              })({
                case _root_.com.daml.quickstart.iou.model.OnlineShop.Product_ReservationCompleted(reservationId) => reservationId
              });
              lte.record(` dataTypeId`, `recordFields `)
            }
          }
        };
        new $anon()
      }
    }
  }
}
